spring:
  profiles: local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/db_example
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      idle-timeout: 10000
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 30
        batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
    properties:
      hibernate:
        jdbc:
          batch_size: 30
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true