spring:
  profiles: local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
    url: jdbc:mysql://localhost:3306/db_example
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
#    dialect: org.hibernate.dialect.H2Dialect
    dialect: org.hibernate.dialect.MySQL5Dialect
    hikari:
      idle-timeout: 10000
      maximumPoolSize: 20
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 30
        batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
    properties:
      hibernate:
        jdbc:
          batch_size: 30
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
youtube:
  url: https://www.googleapis.com/youtube/v3